version: '3'
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - /root/project/bitrix  # Replace with the actual path to your backend app
