on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted

    steps:

      - name: Connect and pull
        run: |
          echo 'hello'
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull"

      - name: Cleanup
        run: |
          ssh-agent -k
          rm -rf ~/.ssh
