name: Deploy to Server

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 45.141.79.120 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 45.141.79.120
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            scp -r ./* root@45.141.79.120:project/onviz_service/