on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: console
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git and SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect and pull
        run: |
          eval "$(ssh-agent)"
          ssh-add ~/.ssh/id_rsa
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      - name: Cleanup
        run: |
          ssh-agent -k
          rm -rf ~/.ssh
