name: Your Workflow Name

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug SSH Agent
        working-directory: ./actions-runner
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -l

      - name: Debug Workflow
        run: |
          pwd
          ls -la /root/project/onviz_service/actions-runner/_work/onviz_service/onviz_service/
          ls -la /root/project/onviz_service/actions-runner/_work/onviz_service/onviz_service/./actions-runner

      - name: Change Directory
        run: cd /root/project/onviz_service/actions-runner/_work/onviz_service/onviz_service/./actions-runner

      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -l
          echo "Start: $(date)"
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 45.141.79.120 >> ~/.ssh/known_hosts
          echo "End: $(date)"
      

      - name: Deploy to Server
        run: |
          scp -r ./* root@45.141.79.120:project/onviz_service/
