name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          chmod 400 /root/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~root/.ssh/id_rsa
          ssh-keyscan -H 45.141.79.120 >> ~root/.ssh/id_rsa

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 45.141.79.120
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            scp -r ./* root@45.141.79.120:project/onviz_service/
