name: Deploy to Server

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: ErrNotNill/ssh-action@master
        with:
          host: ${{ 45.141.79.120 }}
          username: ${{ root }}
          password: ${{ AA1379657aa }}
          script: |
            scp -r ./* ${{ root }}@${{ 45.141.79.120 }}:/project/bitrix/